### ISSUE TITLE
Don't treat #!/usr/bin/env octave ... files as Objective C

### ISSUE THREAD

**Issue by mcandre** [atom/language-objective-c#5]
`*.m` files with `octave` in their shebang should be treated as MATLAB/Octave, not Objective C.

**Comment by 50Wliu** [comment]
@mcandre Is this still an issue in Atom 1.2.4?

**Comment by 50Wliu** [comment]
For some more context:
Currently, once the filetype matches, no more analysis on the file is done to determine what filetype it is.  However, there has been a change in recent Atom versions so that core packages are matched last, which means MATLAB/Octave should get priority now.

**Comment by 50Wliu** [comment]
No response, so closing.  If this is still happening on Atom 1.7.2 or above please comment here.
